# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('webname', models.CharField(blank=True, max_length=20, null=True)),
                ('week_count', models.CharField(blank=True, max_length=100, null=True)),
                ('month_count', models.CharField(blank=True, max_length=500, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('update_count', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'advertiser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secondhand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uname', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('reply_count', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('webname', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('ext1', models.CharField(blank=True, max_length=500, null=True)),
                ('ext2', models.CharField(blank=True, max_length=500, null=True)),
                ('ext3', models.CharField(blank=True, max_length=500, null=True)),
                ('ext4', models.CharField(blank=True, max_length=1000, null=True)),
                ('ext5', models.CharField(blank=True, max_length=10000, null=True)),
                ('update_count', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secondHand',
                'managed': False,
            },
        ),
    ]
